// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: velony/conversation/v1/conversation_user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A user participating in a conversation.
type ConversationUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation user.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The user participating in the conversation.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// The role of the user in the conversation.
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// The time when the conversation user was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The time when the conversation user was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationUser) Reset() {
	*x = ConversationUser{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationUser) ProtoMessage() {}

func (x *ConversationUser) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationUser.ProtoReflect.Descriptor instead.
func (*ConversationUser) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConversationUser) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ConversationUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationUser) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ConversationUser) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// The request message for retrieving a conversation user.
type GetConversationUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation user to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationUserRequest) Reset() {
	*x = GetConversationUserRequest{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationUserRequest) ProtoMessage() {}

func (x *GetConversationUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationUserRequest.ProtoReflect.Descriptor instead.
func (*GetConversationUserRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetConversationUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request message for listing conversation user memberships.
type ListConversationUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation whose user memberships are being listed.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of conversation user memberships to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token received from a previous ListConversationUsers call.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationUsersRequest) Reset() {
	*x = ListConversationUsersRequest{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationUsersRequest) ProtoMessage() {}

func (x *ListConversationUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationUsersRequest.ProtoReflect.Descriptor instead.
func (*ListConversationUsersRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListConversationUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListConversationUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConversationUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// The response message for listing conversation user memberships.
type ListConversationUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation user memberships.
	ConversationUsers []*ConversationUser `protobuf:"bytes,1,rep,name=conversation_users,json=conversationUsers,proto3" json:"conversation_users,omitempty"`
	// A token for retrieving the next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of conversation user memberships.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationUsersResponse) Reset() {
	*x = ListConversationUsersResponse{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationUsersResponse) ProtoMessage() {}

func (x *ListConversationUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationUsersResponse.ProtoReflect.Descriptor instead.
func (*ListConversationUsersResponse) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListConversationUsersResponse) GetConversationUsers() []*ConversationUser {
	if x != nil {
		return x.ConversationUsers
	}
	return nil
}

func (x *ListConversationUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListConversationUsersResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// The request message for retrieving multiple conversation user memberships.
type BatchGetConversationUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation that owns the conversation user memberships.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The resource names of the conversation user memberships to retrieve.
	Names         []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetConversationUsersRequest) Reset() {
	*x = BatchGetConversationUsersRequest{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetConversationUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetConversationUsersRequest) ProtoMessage() {}

func (x *BatchGetConversationUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetConversationUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchGetConversationUsersRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetConversationUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchGetConversationUsersRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// The response message for retrieving multiple conversation user memberships.
type BatchGetConversationUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested conversation user memberships.
	ConversationUsers []*ConversationUser `protobuf:"bytes,1,rep,name=conversation_users,json=conversationUsers,proto3" json:"conversation_users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchGetConversationUsersResponse) Reset() {
	*x = BatchGetConversationUsersResponse{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetConversationUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetConversationUsersResponse) ProtoMessage() {}

func (x *BatchGetConversationUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetConversationUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchGetConversationUsersResponse) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetConversationUsersResponse) GetConversationUsers() []*ConversationUser {
	if x != nil {
		return x.ConversationUsers
	}
	return nil
}

// The request message for creating a conversation user.
type CreateConversationUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation in which to create the conversation user.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The conversation user to create.
	ConversationUser *ConversationUser `protobuf:"bytes,2,opt,name=conversation_user,json=conversationUser,proto3" json:"conversation_user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateConversationUserRequest) Reset() {
	*x = CreateConversationUserRequest{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationUserRequest) ProtoMessage() {}

func (x *CreateConversationUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationUserRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationUserRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateConversationUserRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateConversationUserRequest) GetConversationUser() *ConversationUser {
	if x != nil {
		return x.ConversationUser
	}
	return nil
}

// The request message for updating a conversation user.
type UpdateConversationUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation user to update.
	ConversationUser *ConversationUser `protobuf:"bytes,1,opt,name=conversation_user,json=conversationUser,proto3" json:"conversation_user,omitempty"`
	// The fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationUserRequest) Reset() {
	*x = UpdateConversationUserRequest{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationUserRequest) ProtoMessage() {}

func (x *UpdateConversationUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationUserRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConversationUserRequest) GetConversationUser() *ConversationUser {
	if x != nil {
		return x.ConversationUser
	}
	return nil
}

func (x *UpdateConversationUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// The request message for deleting a conversation user.
type DeleteConversationUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation user to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationUserRequest) Reset() {
	*x = DeleteConversationUserRequest{}
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationUserRequest) ProtoMessage() {}

func (x *DeleteConversationUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationUserRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteConversationUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_velony_conversation_v1_conversation_user_proto protoreflect.FileDescriptor

const file_velony_conversation_v1_conversation_user_proto_rawDesc = "" +
	"\n" +
	".velony/conversation/v1/conversation_user.proto\x12\x16velony.conversation.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x03\n" +
	"\x10ConversationUser\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x120\n" +
	"\x04user\x18\x02 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14user.velony.app/UserR\x04user\x12\x17\n" +
	"\x04role\x18\x03 \x01(\tB\x03\xe0A\x02R\x04role\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime:\x8b\x01\xeaA\x87\x01\n" +
	"(conversation.velony.app/ConversationUser\x126conversations/{conversation}/users/{conversation_user}*\x11conversationUsers2\x10conversationUser\"b\n" +
	"\x1aGetConversationUserRequest\x12D\n" +
	"\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n" +
	"(conversation.velony.app/ConversationUserR\x04name\"\xaa\x01\n" +
	"\x1cListConversationUsersRequest\x12D\n" +
	"\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\"\xbf\x01\n" +
	"\x1dListConversationUsersResponse\x12W\n" +
	"\x12conversation_users\x18\x01 \x03(\v2(.velony.conversation.v1.ConversationUserR\x11conversationUsers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\xb0\x01\n" +
	" BatchGetConversationUsersRequest\x12D\n" +
	"\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x06parent\x12F\n" +
	"\x05names\x18\x02 \x03(\tB0\xe0A\x02\xfaA*\n" +
	"(conversation.velony.app/ConversationUserR\x05names\"|\n" +
	"!BatchGetConversationUsersResponse\x12W\n" +
	"\x12conversation_users\x18\x01 \x03(\v2(.velony.conversation.v1.ConversationUserR\x11conversationUsers\"\xc1\x01\n" +
	"\x1dCreateConversationUserRequest\x12D\n" +
	"\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x06parent\x12Z\n" +
	"\x11conversation_user\x18\x02 \x01(\v2(.velony.conversation.v1.ConversationUserB\x03\xe0A\x02R\x10conversationUser\"\xbd\x01\n" +
	"\x1dUpdateConversationUserRequest\x12Z\n" +
	"\x11conversation_user\x18\x01 \x01(\v2(.velony.conversation.v1.ConversationUserB\x03\xe0A\x02R\x10conversationUser\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"e\n" +
	"\x1dDeleteConversationUserRequest\x12D\n" +
	"\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n" +
	"(conversation.velony.app/ConversationUserR\x04nameB\x8e\x01\n" +
	"\x1aapp.velony.conversation.v1B\x15ConversationUserProtoP\x01Z@github.com/velony-app/conversation/api/velony/conversation/v1;v1\xa2\x02\x14VelonyConversationV1b\x06proto3"

var (
	file_velony_conversation_v1_conversation_user_proto_rawDescOnce sync.Once
	file_velony_conversation_v1_conversation_user_proto_rawDescData []byte
)

func file_velony_conversation_v1_conversation_user_proto_rawDescGZIP() []byte {
	file_velony_conversation_v1_conversation_user_proto_rawDescOnce.Do(func() {
		file_velony_conversation_v1_conversation_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_conversation_user_proto_rawDesc), len(file_velony_conversation_v1_conversation_user_proto_rawDesc)))
	})
	return file_velony_conversation_v1_conversation_user_proto_rawDescData
}

var file_velony_conversation_v1_conversation_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_velony_conversation_v1_conversation_user_proto_goTypes = []any{
	(*ConversationUser)(nil),                  // 0: velony.conversation.v1.ConversationUser
	(*GetConversationUserRequest)(nil),        // 1: velony.conversation.v1.GetConversationUserRequest
	(*ListConversationUsersRequest)(nil),      // 2: velony.conversation.v1.ListConversationUsersRequest
	(*ListConversationUsersResponse)(nil),     // 3: velony.conversation.v1.ListConversationUsersResponse
	(*BatchGetConversationUsersRequest)(nil),  // 4: velony.conversation.v1.BatchGetConversationUsersRequest
	(*BatchGetConversationUsersResponse)(nil), // 5: velony.conversation.v1.BatchGetConversationUsersResponse
	(*CreateConversationUserRequest)(nil),     // 6: velony.conversation.v1.CreateConversationUserRequest
	(*UpdateConversationUserRequest)(nil),     // 7: velony.conversation.v1.UpdateConversationUserRequest
	(*DeleteConversationUserRequest)(nil),     // 8: velony.conversation.v1.DeleteConversationUserRequest
	(*timestamppb.Timestamp)(nil),             // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),             // 10: google.protobuf.FieldMask
}
var file_velony_conversation_v1_conversation_user_proto_depIdxs = []int32{
	9,  // 0: velony.conversation.v1.ConversationUser.create_time:type_name -> google.protobuf.Timestamp
	9,  // 1: velony.conversation.v1.ConversationUser.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: velony.conversation.v1.ListConversationUsersResponse.conversation_users:type_name -> velony.conversation.v1.ConversationUser
	0,  // 3: velony.conversation.v1.BatchGetConversationUsersResponse.conversation_users:type_name -> velony.conversation.v1.ConversationUser
	0,  // 4: velony.conversation.v1.CreateConversationUserRequest.conversation_user:type_name -> velony.conversation.v1.ConversationUser
	0,  // 5: velony.conversation.v1.UpdateConversationUserRequest.conversation_user:type_name -> velony.conversation.v1.ConversationUser
	10, // 6: velony.conversation.v1.UpdateConversationUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_velony_conversation_v1_conversation_user_proto_init() }
func file_velony_conversation_v1_conversation_user_proto_init() {
	if File_velony_conversation_v1_conversation_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_conversation_user_proto_rawDesc), len(file_velony_conversation_v1_conversation_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velony_conversation_v1_conversation_user_proto_goTypes,
		DependencyIndexes: file_velony_conversation_v1_conversation_user_proto_depIdxs,
		MessageInfos:      file_velony_conversation_v1_conversation_user_proto_msgTypes,
	}.Build()
	File_velony_conversation_v1_conversation_user_proto = out.File
	file_velony_conversation_v1_conversation_user_proto_goTypes = nil
	file_velony_conversation_v1_conversation_user_proto_depIdxs = nil
}
