// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: velony/conversation/v1/conversation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A conversation.
type Conversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The title of the conversation.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The avatar image of the conversation.
	AvatarImage string `protobuf:"bytes,3,opt,name=avatar_image,json=avatarImage,proto3" json:"avatar_image,omitempty"`
	// The last message in the conversation.
	LastMessage string `protobuf:"bytes,4,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	// The time when the conversation was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetAvatarImage() string {
	if x != nil {
		return x.AvatarImage
	}
	return ""
}

func (x *Conversation) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Conversation) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// The request message for retrieving a conversation.
type GetConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *GetConversationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request message for listing conversations.
type ListConversationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of conversations to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token received from a previous list request.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *ListConversationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConversationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// The response message for listing conversations.
type ListConversationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversations.
	Conversations []*Conversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	// A token for retrieving the next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The request message for creating a conversation.
type CreateConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation to create.
	Conversation  *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConversationRequest) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// The request message for updating a conversation.
type UpdateConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation to update.
	Conversation *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	// The fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationRequest) Reset() {
	*x = UpdateConversationRequest{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationRequest) ProtoMessage() {}

func (x *UpdateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConversationRequest) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *UpdateConversationRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// The request message for deleting a conversation.
type DeleteConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConversationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request message for replacing a conversation avatar.
type ReplaceConversationAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the conversation.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The avatar image data.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The MIME type of the avatar image data.
	MimeType      string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceConversationAvatarRequest) Reset() {
	*x = ReplaceConversationAvatarRequest{}
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceConversationAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceConversationAvatarRequest) ProtoMessage() {}

func (x *ReplaceConversationAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceConversationAvatarRequest.ProtoReflect.Descriptor instead.
func (*ReplaceConversationAvatarRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *ReplaceConversationAvatarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplaceConversationAvatarRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplaceConversationAvatarRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_velony_conversation_v1_conversation_proto protoreflect.FileDescriptor

const file_velony_conversation_v1_conversation_proto_rawDesc = "" +
	"\n" +
	")velony/conversation/v1/conversation.proto\x12\x16velony.conversation.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x02\n" +
	"\fConversation\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12A\n" +
	"\favatar_image\x18\x03 \x01(\tB\x1e\xe0A\x03\xfaA\x18\n" +
	"\x16media.velony.app/ImageR\vavatarImage\x12J\n" +
	"\flast_message\x18\x04 \x01(\tB'\xe0A\x03\xfaA!\n" +
	"\x1fconversation.velony.app/MessageR\vlastMessage\x12@\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime:d\xeaAa\n" +
	"$conversation.velony.app/Conversation\x12\x1cconversations/{conversation}*\rconversations2\fconversation\"Z\n" +
	"\x16GetConversationRequest\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x04name\"`\n" +
	"\x18ListConversationsRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x03\xe0A\x01R\tpageToken\"\x8f\x01\n" +
	"\x19ListConversationsResponse\x12J\n" +
	"\rconversations\x18\x01 \x03(\v2$.velony.conversation.v1.ConversationR\rconversations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"j\n" +
	"\x19CreateConversationRequest\x12M\n" +
	"\fconversation\x18\x01 \x01(\v2$.velony.conversation.v1.ConversationB\x03\xe0A\x02R\fconversation\"\xac\x01\n" +
	"\x19UpdateConversationRequest\x12M\n" +
	"\fconversation\x18\x01 \x01(\v2$.velony.conversation.v1.ConversationB\x03\xe0A\x02R\fconversation\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"]\n" +
	"\x19DeleteConversationRequest\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x04name\"\x9f\x01\n" +
	" ReplaceConversationAvatarRequest\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x04name\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fB\x03\xe0A\x02R\x04data\x12 \n" +
	"\tmime_type\x18\x03 \x01(\tB\x03\xe0A\x02R\bmimeTypeB\x8a\x01\n" +
	"\x1aapp.velony.conversation.v1B\x11ConversationProtoP\x01Z@github.com/velony-app/conversation/api/velony/conversation/v1;v1\xa2\x02\x14VelonyConversationV1b\x06proto3"

var (
	file_velony_conversation_v1_conversation_proto_rawDescOnce sync.Once
	file_velony_conversation_v1_conversation_proto_rawDescData []byte
)

func file_velony_conversation_v1_conversation_proto_rawDescGZIP() []byte {
	file_velony_conversation_v1_conversation_proto_rawDescOnce.Do(func() {
		file_velony_conversation_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_conversation_proto_rawDesc), len(file_velony_conversation_v1_conversation_proto_rawDesc)))
	})
	return file_velony_conversation_v1_conversation_proto_rawDescData
}

var file_velony_conversation_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_velony_conversation_v1_conversation_proto_goTypes = []any{
	(*Conversation)(nil),                     // 0: velony.conversation.v1.Conversation
	(*GetConversationRequest)(nil),           // 1: velony.conversation.v1.GetConversationRequest
	(*ListConversationsRequest)(nil),         // 2: velony.conversation.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil),        // 3: velony.conversation.v1.ListConversationsResponse
	(*CreateConversationRequest)(nil),        // 4: velony.conversation.v1.CreateConversationRequest
	(*UpdateConversationRequest)(nil),        // 5: velony.conversation.v1.UpdateConversationRequest
	(*DeleteConversationRequest)(nil),        // 6: velony.conversation.v1.DeleteConversationRequest
	(*ReplaceConversationAvatarRequest)(nil), // 7: velony.conversation.v1.ReplaceConversationAvatarRequest
	(*timestamppb.Timestamp)(nil),            // 8: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),            // 9: google.protobuf.FieldMask
}
var file_velony_conversation_v1_conversation_proto_depIdxs = []int32{
	8, // 0: velony.conversation.v1.Conversation.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: velony.conversation.v1.ListConversationsResponse.conversations:type_name -> velony.conversation.v1.Conversation
	0, // 2: velony.conversation.v1.CreateConversationRequest.conversation:type_name -> velony.conversation.v1.Conversation
	0, // 3: velony.conversation.v1.UpdateConversationRequest.conversation:type_name -> velony.conversation.v1.Conversation
	9, // 4: velony.conversation.v1.UpdateConversationRequest.update_mask:type_name -> google.protobuf.FieldMask
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_velony_conversation_v1_conversation_proto_init() }
func file_velony_conversation_v1_conversation_proto_init() {
	if File_velony_conversation_v1_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_conversation_proto_rawDesc), len(file_velony_conversation_v1_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velony_conversation_v1_conversation_proto_goTypes,
		DependencyIndexes: file_velony_conversation_v1_conversation_proto_depIdxs,
		MessageInfos:      file_velony_conversation_v1_conversation_proto_msgTypes,
	}.Build()
	File_velony_conversation_v1_conversation_proto = out.File
	file_velony_conversation_v1_conversation_proto_goTypes = nil
	file_velony_conversation_v1_conversation_proto_depIdxs = nil
}
