// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: velony/conversation/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines machine-readable error reasons returned by the Conversation API.
//
// These values are used as the `reason` field of `google.rpc.ErrorInfo` with
// the error domain `conversation.velony.app`.
//
// This enum is not frozen and new values may be added in the future.
type ErrorReason int32

const (
	// Do not use this default value.
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// The requested conversation does not exist.
	ErrorReason_CONVERSATION_NOT_FOUND ErrorReason = 1
	// The requested message does not exist.
	ErrorReason_MESSAGE_NOT_FOUND ErrorReason = 2
	// The requested conversation user does not exist.
	ErrorReason_CONVERSATION_USER_NOT_FOUND ErrorReason = 3
	// The user is already a member of the conversation.
	ErrorReason_CONVERSATION_USER_ALREADY_EXISTS ErrorReason = 4
	// The conversation contains child resources and cannot be deleted.
	ErrorReason_CONVERSATION_NOT_EMPTY ErrorReason = 5
	// The caller does not have permission to perform the requested operation.
	ErrorReason_INSUFFICIENT_PERMISSION ErrorReason = 6
	// A resource name has an invalid format.
	ErrorReason_RESOURCE_NAME_INVALID ErrorReason = 7
	// A resource does not belong to the parent specified in the request.
	ErrorReason_RESOURCE_PARENT_MISMATCH ErrorReason = 8
	// A batch get request does not contain any resource names.
	ErrorReason_BATCH_NAMES_EMPTY ErrorReason = 9
	// The update mask contains an invalid or unsupported field path.
	ErrorReason_UPDATE_MASK_INVALID ErrorReason = 10
	// The conversation title is invalid.
	ErrorReason_CONVERSATION_TITLE_INVALID ErrorReason = 11
	// The message content is invalid.
	ErrorReason_MESSAGE_CONTENT_INVALID ErrorReason = 12
	// The conversation user role is invalid or unsupported.
	ErrorReason_CONVERSATION_USER_ROLE_INVALID ErrorReason = 13
	// The avatar data is not a valid image.
	ErrorReason_AVATAR_DATA_INVALID ErrorReason = 14
	// The avatar MIME type is not supported.
	ErrorReason_AVATAR_MIME_TYPE_UNSUPPORTED ErrorReason = 15
	// The declared avatar MIME type does not match the avatar data.
	ErrorReason_AVATAR_MIME_TYPE_MISMATCH ErrorReason = 16
	// The avatar exceeds the maximum allowed size.
	ErrorReason_AVATAR_TOO_LARGE ErrorReason = 17
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "CONVERSATION_NOT_FOUND",
		2:  "MESSAGE_NOT_FOUND",
		3:  "CONVERSATION_USER_NOT_FOUND",
		4:  "CONVERSATION_USER_ALREADY_EXISTS",
		5:  "CONVERSATION_NOT_EMPTY",
		6:  "INSUFFICIENT_PERMISSION",
		7:  "RESOURCE_NAME_INVALID",
		8:  "RESOURCE_PARENT_MISMATCH",
		9:  "BATCH_NAMES_EMPTY",
		10: "UPDATE_MASK_INVALID",
		11: "CONVERSATION_TITLE_INVALID",
		12: "MESSAGE_CONTENT_INVALID",
		13: "CONVERSATION_USER_ROLE_INVALID",
		14: "AVATAR_DATA_INVALID",
		15: "AVATAR_MIME_TYPE_UNSUPPORTED",
		16: "AVATAR_MIME_TYPE_MISMATCH",
		17: "AVATAR_TOO_LARGE",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":         0,
		"CONVERSATION_NOT_FOUND":           1,
		"MESSAGE_NOT_FOUND":                2,
		"CONVERSATION_USER_NOT_FOUND":      3,
		"CONVERSATION_USER_ALREADY_EXISTS": 4,
		"CONVERSATION_NOT_EMPTY":           5,
		"INSUFFICIENT_PERMISSION":          6,
		"RESOURCE_NAME_INVALID":            7,
		"RESOURCE_PARENT_MISMATCH":         8,
		"BATCH_NAMES_EMPTY":                9,
		"UPDATE_MASK_INVALID":              10,
		"CONVERSATION_TITLE_INVALID":       11,
		"MESSAGE_CONTENT_INVALID":          12,
		"CONVERSATION_USER_ROLE_INVALID":   13,
		"AVATAR_DATA_INVALID":              14,
		"AVATAR_MIME_TYPE_UNSUPPORTED":     15,
		"AVATAR_MIME_TYPE_MISMATCH":        16,
		"AVATAR_TOO_LARGE":                 17,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_velony_conversation_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_velony_conversation_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_velony_conversation_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_velony_conversation_v1_error_reason_proto protoreflect.FileDescriptor

const file_velony_conversation_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	")velony/conversation/v1/error_reason.proto\x12\x16velony.conversation.v1*\x98\x04\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONVERSATION_NOT_FOUND\x10\x01\x12\x15\n" +
	"\x11MESSAGE_NOT_FOUND\x10\x02\x12\x1f\n" +
	"\x1bCONVERSATION_USER_NOT_FOUND\x10\x03\x12$\n" +
	" CONVERSATION_USER_ALREADY_EXISTS\x10\x04\x12\x1a\n" +
	"\x16CONVERSATION_NOT_EMPTY\x10\x05\x12\x1b\n" +
	"\x17INSUFFICIENT_PERMISSION\x10\x06\x12\x19\n" +
	"\x15RESOURCE_NAME_INVALID\x10\a\x12\x1c\n" +
	"\x18RESOURCE_PARENT_MISMATCH\x10\b\x12\x15\n" +
	"\x11BATCH_NAMES_EMPTY\x10\t\x12\x17\n" +
	"\x13UPDATE_MASK_INVALID\x10\n" +
	"\x12\x1e\n" +
	"\x1aCONVERSATION_TITLE_INVALID\x10\v\x12\x1b\n" +
	"\x17MESSAGE_CONTENT_INVALID\x10\f\x12\"\n" +
	"\x1eCONVERSATION_USER_ROLE_INVALID\x10\r\x12\x17\n" +
	"\x13AVATAR_DATA_INVALID\x10\x0e\x12 \n" +
	"\x1cAVATAR_MIME_TYPE_UNSUPPORTED\x10\x0f\x12\x1d\n" +
	"\x19AVATAR_MIME_TYPE_MISMATCH\x10\x10\x12\x14\n" +
	"\x10AVATAR_TOO_LARGE\x10\x11B\x89\x01\n" +
	"\x1aapp.velony.conversation.v1B\x10ErrorReasonProtoP\x01Z@github.com/velony-app/conversation/api/velony/conversation/v1;v1\xa2\x02\x14VelonyConversationV1b\x06proto3"

var (
	file_velony_conversation_v1_error_reason_proto_rawDescOnce sync.Once
	file_velony_conversation_v1_error_reason_proto_rawDescData []byte
)

func file_velony_conversation_v1_error_reason_proto_rawDescGZIP() []byte {
	file_velony_conversation_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_velony_conversation_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_error_reason_proto_rawDesc), len(file_velony_conversation_v1_error_reason_proto_rawDesc)))
	})
	return file_velony_conversation_v1_error_reason_proto_rawDescData
}

var file_velony_conversation_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_velony_conversation_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: velony.conversation.v1.ErrorReason
}
var file_velony_conversation_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_velony_conversation_v1_error_reason_proto_init() }
func file_velony_conversation_v1_error_reason_proto_init() {
	if File_velony_conversation_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_error_reason_proto_rawDesc), len(file_velony_conversation_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velony_conversation_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_velony_conversation_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_velony_conversation_v1_error_reason_proto_enumTypes,
	}.Build()
	File_velony_conversation_v1_error_reason_proto = out.File
	file_velony_conversation_v1_error_reason_proto_goTypes = nil
	file_velony_conversation_v1_error_reason_proto_depIdxs = nil
}
