// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: velony/conversation/v1/message.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message in a conversation.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the message.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The user that sent the message.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// The content of the message.
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// The time when the message was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The time when the message was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Message) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// The request message for retrieving a message.
type GetMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the message to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request message for listing messages.
type ListMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation whose messages are being listed.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of messages to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token received from a previous ListMessages call.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *ListMessagesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// The response message for listing messages.
type ListMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The messages.
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// A token for retrieving the next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The request message for retrieving multiple messages.
type BatchGetMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation that owns the messages.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The resource names of the messages to retrieve.
	Names         []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMessagesRequest) Reset() {
	*x = BatchGetMessagesRequest{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMessagesRequest) ProtoMessage() {}

func (x *BatchGetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMessagesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetMessagesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchGetMessagesRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// The response message for retrieving multiple messages.
type BatchGetMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested messages.
	Messages      []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMessagesResponse) Reset() {
	*x = BatchGetMessagesResponse{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMessagesResponse) ProtoMessage() {}

func (x *BatchGetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMessagesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// The request message for creating a message.
type CreateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The conversation in which to create the message.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The message to create.
	Message       *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMessageRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// The request message for updating a message.
type UpdateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message to update.
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UpdateMessageRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// The request message for deleting a message.
type DeleteMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the message to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_velony_conversation_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velony_conversation_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_velony_conversation_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_velony_conversation_v1_message_proto protoreflect.FileDescriptor

const file_velony_conversation_v1_message_proto_rawDesc = "" +
	"\n" +
	"$velony/conversation/v1/message.proto\x12\x16velony.conversation.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x02\n" +
	"\aMessage\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x120\n" +
	"\x04user\x18\x02 \x01(\tB\x1c\xe0A\x03\xfaA\x16\n" +
	"\x14user.velony.app/UserR\x04user\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tB\x03\xe0A\x02R\acontent\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime:h\xeaAe\n" +
	"\x1fconversation.velony.app/Message\x12/conversations/{conversation}/messages/{message}*\bmessages2\amessage\"P\n" +
	"\x11GetMessageRequest\x12;\n" +
	"\x04name\x18\x01 \x01(\tB'\xe0A\x02\xfaA!\n" +
	"\x1fconversation.velony.app/MessageR\x04name\"\xa1\x01\n" +
	"\x13ListMessagesRequest\x12D\n" +
	"\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\"{\n" +
	"\x14ListMessagesResponse\x12;\n" +
	"\bmessages\x18\x01 \x03(\v2\x1f.velony.conversation.v1.MessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9e\x01\n" +
	"\x17BatchGetMessagesRequest\x12D\n" +
	"\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x06parent\x12=\n" +
	"\x05names\x18\x02 \x03(\tB'\xe0A\x02\xfaA!\n" +
	"\x1fconversation.velony.app/MessageR\x05names\"W\n" +
	"\x18BatchGetMessagesResponse\x12;\n" +
	"\bmessages\x18\x01 \x03(\v2\x1f.velony.conversation.v1.MessageR\bmessages\"\x9c\x01\n" +
	"\x14CreateMessageRequest\x12D\n" +
	"\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n" +
	"$conversation.velony.app/ConversationR\x06parent\x12>\n" +
	"\amessage\x18\x02 \x01(\v2\x1f.velony.conversation.v1.MessageB\x03\xe0A\x02R\amessage\"\x98\x01\n" +
	"\x14UpdateMessageRequest\x12>\n" +
	"\amessage\x18\x01 \x01(\v2\x1f.velony.conversation.v1.MessageB\x03\xe0A\x02R\amessage\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"S\n" +
	"\x14DeleteMessageRequest\x12;\n" +
	"\x04name\x18\x01 \x01(\tB'\xe0A\x02\xfaA!\n" +
	"\x1fconversation.velony.app/MessageR\x04nameB\x85\x01\n" +
	"\x1aapp.velony.conversation.v1B\fMessageProtoP\x01Z@github.com/velony-app/conversation/api/velony/conversation/v1;v1\xa2\x02\x14VelonyConversationV1b\x06proto3"

var (
	file_velony_conversation_v1_message_proto_rawDescOnce sync.Once
	file_velony_conversation_v1_message_proto_rawDescData []byte
)

func file_velony_conversation_v1_message_proto_rawDescGZIP() []byte {
	file_velony_conversation_v1_message_proto_rawDescOnce.Do(func() {
		file_velony_conversation_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_message_proto_rawDesc), len(file_velony_conversation_v1_message_proto_rawDesc)))
	})
	return file_velony_conversation_v1_message_proto_rawDescData
}

var file_velony_conversation_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_velony_conversation_v1_message_proto_goTypes = []any{
	(*Message)(nil),                  // 0: velony.conversation.v1.Message
	(*GetMessageRequest)(nil),        // 1: velony.conversation.v1.GetMessageRequest
	(*ListMessagesRequest)(nil),      // 2: velony.conversation.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),     // 3: velony.conversation.v1.ListMessagesResponse
	(*BatchGetMessagesRequest)(nil),  // 4: velony.conversation.v1.BatchGetMessagesRequest
	(*BatchGetMessagesResponse)(nil), // 5: velony.conversation.v1.BatchGetMessagesResponse
	(*CreateMessageRequest)(nil),     // 6: velony.conversation.v1.CreateMessageRequest
	(*UpdateMessageRequest)(nil),     // 7: velony.conversation.v1.UpdateMessageRequest
	(*DeleteMessageRequest)(nil),     // 8: velony.conversation.v1.DeleteMessageRequest
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 10: google.protobuf.FieldMask
}
var file_velony_conversation_v1_message_proto_depIdxs = []int32{
	9,  // 0: velony.conversation.v1.Message.create_time:type_name -> google.protobuf.Timestamp
	9,  // 1: velony.conversation.v1.Message.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: velony.conversation.v1.ListMessagesResponse.messages:type_name -> velony.conversation.v1.Message
	0,  // 3: velony.conversation.v1.BatchGetMessagesResponse.messages:type_name -> velony.conversation.v1.Message
	0,  // 4: velony.conversation.v1.CreateMessageRequest.message:type_name -> velony.conversation.v1.Message
	0,  // 5: velony.conversation.v1.UpdateMessageRequest.message:type_name -> velony.conversation.v1.Message
	10, // 6: velony.conversation.v1.UpdateMessageRequest.update_mask:type_name -> google.protobuf.FieldMask
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_velony_conversation_v1_message_proto_init() }
func file_velony_conversation_v1_message_proto_init() {
	if File_velony_conversation_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_message_proto_rawDesc), len(file_velony_conversation_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velony_conversation_v1_message_proto_goTypes,
		DependencyIndexes: file_velony_conversation_v1_message_proto_depIdxs,
		MessageInfos:      file_velony_conversation_v1_message_proto_msgTypes,
	}.Build()
	File_velony_conversation_v1_message_proto = out.File
	file_velony_conversation_v1_message_proto_goTypes = nil
	file_velony_conversation_v1_message_proto_depIdxs = nil
}
