// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: velony/conversation/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_velony_conversation_v1_service_proto protoreflect.FileDescriptor

const file_velony_conversation_v1_service_proto_rawDesc = "" +
	"\n" +
	"$velony/conversation/v1/service.proto\x12\x16velony.conversation.v1\x1a)velony/conversation/v1/conversation.proto\x1a.velony/conversation/v1/conversation_user.proto\x1a$velony/conversation/v1/message.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1bgoogle/protobuf/empty.proto2\xef\x18\n" +
	"\x13ConversationService\x12\x92\x01\n" +
	"\x0fGetConversation\x12..velony.conversation.v1.GetConversationRequest\x1a$.velony.conversation.v1.Conversation\")\xdaA\x04name\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/{name=conversations/*}\x12\x93\x01\n" +
	"\x11ListConversations\x120.velony.conversation.v1.ListConversationsRequest\x1a1.velony.conversation.v1.ListConversationsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/conversations\x12\xa5\x01\n" +
	"\x12CreateConversation\x121.velony.conversation.v1.CreateConversationRequest\x1a$.velony.conversation.v1.Conversation\"6\xdaA\fconversation\x82\xd3\xe4\x93\x02!:\fconversation\"\x11/v1/conversations\x12\xc7\x01\n" +
	"\x12UpdateConversation\x121.velony.conversation.v1.UpdateConversationRequest\x1a$.velony.conversation.v1.Conversation\"X\xdaA\x18conversation,update_mask\x82\xd3\xe4\x93\x027:\fconversation2'/v1/{conversation.name=conversations/*}\x12\x8a\x01\n" +
	"\x12DeleteConversation\x121.velony.conversation.v1.DeleteConversationRequest\x1a\x16.google.protobuf.Empty\")\xdaA\x04name\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/{name=conversations/*}\x12\x8e\x01\n" +
	"\n" +
	"GetMessage\x12).velony.conversation.v1.GetMessageRequest\x1a\x1f.velony.conversation.v1.Message\"4\xdaA\x04name\x82\xd3\xe4\x93\x02'\x12%/v1/{name=conversations/*/messages/*}\x12\xa1\x01\n" +
	"\fListMessages\x12+.velony.conversation.v1.ListMessagesRequest\x1a,.velony.conversation.v1.ListMessagesResponse\"6\xdaA\x06parent\x82\xd3\xe4\x93\x02'\x12%/v1/{parent=conversations/*}/messages\x12\xad\x01\n" +
	"\x10BatchGetMessages\x12/.velony.conversation.v1.BatchGetMessagesRequest\x1a0.velony.conversation.v1.BatchGetMessagesResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/{parent=conversations/*}/messages:batchGet\x12\xa7\x01\n" +
	"\rCreateMessage\x12,.velony.conversation.v1.CreateMessageRequest\x1a\x1f.velony.conversation.v1.Message\"G\xdaA\x0eparent,message\x82\xd3\xe4\x93\x020:\amessage\"%/v1/{parent=conversations/*}/messages\x12\xb4\x01\n" +
	"\rUpdateMessage\x12,.velony.conversation.v1.UpdateMessageRequest\x1a\x1f.velony.conversation.v1.Message\"T\xdaA\x13message,update_mask\x82\xd3\xe4\x93\x028:\amessage2-/v1/{message.name=conversations/*/messages/*}\x12\x8b\x01\n" +
	"\rDeleteMessage\x12,.velony.conversation.v1.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\"4\xdaA\x04name\x82\xd3\xe4\x93\x02'*%/v1/{name=conversations/*/messages/*}\x12\xa6\x01\n" +
	"\x13GetConversationUser\x122.velony.conversation.v1.GetConversationUserRequest\x1a(.velony.conversation.v1.ConversationUser\"1\xdaA\x04name\x82\xd3\xe4\x93\x02$\x12\"/v1/{name=conversations/*/users/*}\x12\xb9\x01\n" +
	"\x15ListConversationUsers\x124.velony.conversation.v1.ListConversationUsersRequest\x1a5.velony.conversation.v1.ListConversationUsersResponse\"3\xdaA\x06parent\x82\xd3\xe4\x93\x02$\x12\"/v1/{parent=conversations/*}/users\x12\xc5\x01\n" +
	"\x19BatchGetConversationUsers\x128.velony.conversation.v1.BatchGetConversationUsersRequest\x1a9.velony.conversation.v1.BatchGetConversationUsersResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=conversations/*}/users:batchGet\x12\xd3\x01\n" +
	"\x16CreateConversationUser\x125.velony.conversation.v1.CreateConversationUserRequest\x1a(.velony.conversation.v1.ConversationUser\"X\xdaA\x18parent,conversation_user\x82\xd3\xe4\x93\x027:\x11conversation_user\"\"/v1/{parent=conversations/*}/users\x12\xea\x01\n" +
	"\x16UpdateConversationUser\x125.velony.conversation.v1.UpdateConversationUserRequest\x1a(.velony.conversation.v1.ConversationUser\"o\xdaA\x1dconversation_user,update_mask\x82\xd3\xe4\x93\x02I:\x11conversation_user24/v1/{conversation_user.name=conversations/*/users/*}\x12\x9a\x01\n" +
	"\x16DeleteConversationUser\x125.velony.conversation.v1.DeleteConversationUserRequest\x1a\x16.google.protobuf.Empty\"1\xdaA\x04name\x82\xd3\xe4\x93\x02$*\"/v1/{name=conversations/*/users/*}\x12\xb0\x01\n" +
	"\x19ReplaceConversationAvatar\x128.velony.conversation.v1.ReplaceConversationAvatarRequest\x1a$.velony.conversation.v1.Conversation\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/{name=conversations/*}:replaceAvatar\x1a\x1a\xcaA\x17conversation.velony.appB\x85\x01\n" +
	"\x1aapp.velony.conversation.v1B\fServiceProtoP\x01Z@github.com/velony-app/conversation/api/velony/conversation/v1;v1\xa2\x02\x14VelonyConversationV1b\x06proto3"

var file_velony_conversation_v1_service_proto_goTypes = []any{
	(*GetConversationRequest)(nil),            // 0: velony.conversation.v1.GetConversationRequest
	(*ListConversationsRequest)(nil),          // 1: velony.conversation.v1.ListConversationsRequest
	(*CreateConversationRequest)(nil),         // 2: velony.conversation.v1.CreateConversationRequest
	(*UpdateConversationRequest)(nil),         // 3: velony.conversation.v1.UpdateConversationRequest
	(*DeleteConversationRequest)(nil),         // 4: velony.conversation.v1.DeleteConversationRequest
	(*GetMessageRequest)(nil),                 // 5: velony.conversation.v1.GetMessageRequest
	(*ListMessagesRequest)(nil),               // 6: velony.conversation.v1.ListMessagesRequest
	(*BatchGetMessagesRequest)(nil),           // 7: velony.conversation.v1.BatchGetMessagesRequest
	(*CreateMessageRequest)(nil),              // 8: velony.conversation.v1.CreateMessageRequest
	(*UpdateMessageRequest)(nil),              // 9: velony.conversation.v1.UpdateMessageRequest
	(*DeleteMessageRequest)(nil),              // 10: velony.conversation.v1.DeleteMessageRequest
	(*GetConversationUserRequest)(nil),        // 11: velony.conversation.v1.GetConversationUserRequest
	(*ListConversationUsersRequest)(nil),      // 12: velony.conversation.v1.ListConversationUsersRequest
	(*BatchGetConversationUsersRequest)(nil),  // 13: velony.conversation.v1.BatchGetConversationUsersRequest
	(*CreateConversationUserRequest)(nil),     // 14: velony.conversation.v1.CreateConversationUserRequest
	(*UpdateConversationUserRequest)(nil),     // 15: velony.conversation.v1.UpdateConversationUserRequest
	(*DeleteConversationUserRequest)(nil),     // 16: velony.conversation.v1.DeleteConversationUserRequest
	(*ReplaceConversationAvatarRequest)(nil),  // 17: velony.conversation.v1.ReplaceConversationAvatarRequest
	(*Conversation)(nil),                      // 18: velony.conversation.v1.Conversation
	(*ListConversationsResponse)(nil),         // 19: velony.conversation.v1.ListConversationsResponse
	(*emptypb.Empty)(nil),                     // 20: google.protobuf.Empty
	(*Message)(nil),                           // 21: velony.conversation.v1.Message
	(*ListMessagesResponse)(nil),              // 22: velony.conversation.v1.ListMessagesResponse
	(*BatchGetMessagesResponse)(nil),          // 23: velony.conversation.v1.BatchGetMessagesResponse
	(*ConversationUser)(nil),                  // 24: velony.conversation.v1.ConversationUser
	(*ListConversationUsersResponse)(nil),     // 25: velony.conversation.v1.ListConversationUsersResponse
	(*BatchGetConversationUsersResponse)(nil), // 26: velony.conversation.v1.BatchGetConversationUsersResponse
}
var file_velony_conversation_v1_service_proto_depIdxs = []int32{
	0,  // 0: velony.conversation.v1.ConversationService.GetConversation:input_type -> velony.conversation.v1.GetConversationRequest
	1,  // 1: velony.conversation.v1.ConversationService.ListConversations:input_type -> velony.conversation.v1.ListConversationsRequest
	2,  // 2: velony.conversation.v1.ConversationService.CreateConversation:input_type -> velony.conversation.v1.CreateConversationRequest
	3,  // 3: velony.conversation.v1.ConversationService.UpdateConversation:input_type -> velony.conversation.v1.UpdateConversationRequest
	4,  // 4: velony.conversation.v1.ConversationService.DeleteConversation:input_type -> velony.conversation.v1.DeleteConversationRequest
	5,  // 5: velony.conversation.v1.ConversationService.GetMessage:input_type -> velony.conversation.v1.GetMessageRequest
	6,  // 6: velony.conversation.v1.ConversationService.ListMessages:input_type -> velony.conversation.v1.ListMessagesRequest
	7,  // 7: velony.conversation.v1.ConversationService.BatchGetMessages:input_type -> velony.conversation.v1.BatchGetMessagesRequest
	8,  // 8: velony.conversation.v1.ConversationService.CreateMessage:input_type -> velony.conversation.v1.CreateMessageRequest
	9,  // 9: velony.conversation.v1.ConversationService.UpdateMessage:input_type -> velony.conversation.v1.UpdateMessageRequest
	10, // 10: velony.conversation.v1.ConversationService.DeleteMessage:input_type -> velony.conversation.v1.DeleteMessageRequest
	11, // 11: velony.conversation.v1.ConversationService.GetConversationUser:input_type -> velony.conversation.v1.GetConversationUserRequest
	12, // 12: velony.conversation.v1.ConversationService.ListConversationUsers:input_type -> velony.conversation.v1.ListConversationUsersRequest
	13, // 13: velony.conversation.v1.ConversationService.BatchGetConversationUsers:input_type -> velony.conversation.v1.BatchGetConversationUsersRequest
	14, // 14: velony.conversation.v1.ConversationService.CreateConversationUser:input_type -> velony.conversation.v1.CreateConversationUserRequest
	15, // 15: velony.conversation.v1.ConversationService.UpdateConversationUser:input_type -> velony.conversation.v1.UpdateConversationUserRequest
	16, // 16: velony.conversation.v1.ConversationService.DeleteConversationUser:input_type -> velony.conversation.v1.DeleteConversationUserRequest
	17, // 17: velony.conversation.v1.ConversationService.ReplaceConversationAvatar:input_type -> velony.conversation.v1.ReplaceConversationAvatarRequest
	18, // 18: velony.conversation.v1.ConversationService.GetConversation:output_type -> velony.conversation.v1.Conversation
	19, // 19: velony.conversation.v1.ConversationService.ListConversations:output_type -> velony.conversation.v1.ListConversationsResponse
	18, // 20: velony.conversation.v1.ConversationService.CreateConversation:output_type -> velony.conversation.v1.Conversation
	18, // 21: velony.conversation.v1.ConversationService.UpdateConversation:output_type -> velony.conversation.v1.Conversation
	20, // 22: velony.conversation.v1.ConversationService.DeleteConversation:output_type -> google.protobuf.Empty
	21, // 23: velony.conversation.v1.ConversationService.GetMessage:output_type -> velony.conversation.v1.Message
	22, // 24: velony.conversation.v1.ConversationService.ListMessages:output_type -> velony.conversation.v1.ListMessagesResponse
	23, // 25: velony.conversation.v1.ConversationService.BatchGetMessages:output_type -> velony.conversation.v1.BatchGetMessagesResponse
	21, // 26: velony.conversation.v1.ConversationService.CreateMessage:output_type -> velony.conversation.v1.Message
	21, // 27: velony.conversation.v1.ConversationService.UpdateMessage:output_type -> velony.conversation.v1.Message
	20, // 28: velony.conversation.v1.ConversationService.DeleteMessage:output_type -> google.protobuf.Empty
	24, // 29: velony.conversation.v1.ConversationService.GetConversationUser:output_type -> velony.conversation.v1.ConversationUser
	25, // 30: velony.conversation.v1.ConversationService.ListConversationUsers:output_type -> velony.conversation.v1.ListConversationUsersResponse
	26, // 31: velony.conversation.v1.ConversationService.BatchGetConversationUsers:output_type -> velony.conversation.v1.BatchGetConversationUsersResponse
	24, // 32: velony.conversation.v1.ConversationService.CreateConversationUser:output_type -> velony.conversation.v1.ConversationUser
	24, // 33: velony.conversation.v1.ConversationService.UpdateConversationUser:output_type -> velony.conversation.v1.ConversationUser
	20, // 34: velony.conversation.v1.ConversationService.DeleteConversationUser:output_type -> google.protobuf.Empty
	18, // 35: velony.conversation.v1.ConversationService.ReplaceConversationAvatar:output_type -> velony.conversation.v1.Conversation
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_velony_conversation_v1_service_proto_init() }
func file_velony_conversation_v1_service_proto_init() {
	if File_velony_conversation_v1_service_proto != nil {
		return
	}
	file_velony_conversation_v1_conversation_proto_init()
	file_velony_conversation_v1_conversation_user_proto_init()
	file_velony_conversation_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velony_conversation_v1_service_proto_rawDesc), len(file_velony_conversation_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_velony_conversation_v1_service_proto_goTypes,
		DependencyIndexes: file_velony_conversation_v1_service_proto_depIdxs,
	}.Build()
	File_velony_conversation_v1_service_proto = out.File
	file_velony_conversation_v1_service_proto_goTypes = nil
	file_velony_conversation_v1_service_proto_depIdxs = nil
}
