// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: velony/conversation/v1/service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationConversationServiceBatchGetConversationUsers = "/velony.conversation.v1.ConversationService/BatchGetConversationUsers"
const OperationConversationServiceBatchGetMessages = "/velony.conversation.v1.ConversationService/BatchGetMessages"
const OperationConversationServiceCreateConversation = "/velony.conversation.v1.ConversationService/CreateConversation"
const OperationConversationServiceCreateConversationUser = "/velony.conversation.v1.ConversationService/CreateConversationUser"
const OperationConversationServiceCreateMessage = "/velony.conversation.v1.ConversationService/CreateMessage"
const OperationConversationServiceDeleteConversation = "/velony.conversation.v1.ConversationService/DeleteConversation"
const OperationConversationServiceDeleteConversationUser = "/velony.conversation.v1.ConversationService/DeleteConversationUser"
const OperationConversationServiceDeleteMessage = "/velony.conversation.v1.ConversationService/DeleteMessage"
const OperationConversationServiceGetConversation = "/velony.conversation.v1.ConversationService/GetConversation"
const OperationConversationServiceGetConversationUser = "/velony.conversation.v1.ConversationService/GetConversationUser"
const OperationConversationServiceGetMessage = "/velony.conversation.v1.ConversationService/GetMessage"
const OperationConversationServiceListConversationUsers = "/velony.conversation.v1.ConversationService/ListConversationUsers"
const OperationConversationServiceListConversations = "/velony.conversation.v1.ConversationService/ListConversations"
const OperationConversationServiceListMessages = "/velony.conversation.v1.ConversationService/ListMessages"
const OperationConversationServiceReplaceConversationAvatar = "/velony.conversation.v1.ConversationService/ReplaceConversationAvatar"
const OperationConversationServiceUpdateConversation = "/velony.conversation.v1.ConversationService/UpdateConversation"
const OperationConversationServiceUpdateConversationUser = "/velony.conversation.v1.ConversationService/UpdateConversationUser"
const OperationConversationServiceUpdateMessage = "/velony.conversation.v1.ConversationService/UpdateMessage"

type ConversationServiceHTTPServer interface {
	// BatchGetConversationUsers Retrieves multiple conversation users.
	BatchGetConversationUsers(context.Context, *BatchGetConversationUsersRequest) (*BatchGetConversationUsersResponse, error)
	// BatchGetMessages Retrieves multiple messages.
	BatchGetMessages(context.Context, *BatchGetMessagesRequest) (*BatchGetMessagesResponse, error)
	// CreateConversation Creates a conversation.
	CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error)
	// CreateConversationUser Creates a conversation user.
	CreateConversationUser(context.Context, *CreateConversationUserRequest) (*ConversationUser, error)
	// CreateMessage Creates a message.
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	// DeleteConversation Deletes a conversation.
	DeleteConversation(context.Context, *DeleteConversationRequest) (*emptypb.Empty, error)
	// DeleteConversationUser Deletes a conversation user.
	DeleteConversationUser(context.Context, *DeleteConversationUserRequest) (*emptypb.Empty, error)
	// DeleteMessage Deletes a message.
	DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error)
	// GetConversation Retrieves a conversation.
	GetConversation(context.Context, *GetConversationRequest) (*Conversation, error)
	// GetConversationUser Retrieves a conversation user.
	GetConversationUser(context.Context, *GetConversationUserRequest) (*ConversationUser, error)
	// GetMessage Retrieves a message.
	GetMessage(context.Context, *GetMessageRequest) (*Message, error)
	// ListConversationUsers Lists user memberships in a conversation.
	ListConversationUsers(context.Context, *ListConversationUsersRequest) (*ListConversationUsersResponse, error)
	// ListConversations Lists conversations.
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	// ListMessages Lists messages in a conversation.
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	// ReplaceConversationAvatar Replaces the avatar of a conversation.
	ReplaceConversationAvatar(context.Context, *ReplaceConversationAvatarRequest) (*Conversation, error)
	// UpdateConversation Updates a conversation.
	UpdateConversation(context.Context, *UpdateConversationRequest) (*Conversation, error)
	// UpdateConversationUser Updates a conversation user.
	UpdateConversationUser(context.Context, *UpdateConversationUserRequest) (*ConversationUser, error)
	// UpdateMessage Updates a message.
	UpdateMessage(context.Context, *UpdateMessageRequest) (*Message, error)
}

func RegisterConversationServiceHTTPServer(s *http.Server, srv ConversationServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/{name:conversations/[^/]+}", _ConversationService_GetConversation0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/conversations", _ConversationService_ListConversations0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/conversations", _ConversationService_CreateConversation0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/{conversation.name:conversations/[^/]+}", _ConversationService_UpdateConversation0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/{name:conversations/[^/]+}", _ConversationService_DeleteConversation0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{name:conversations/[^/]+/messages/[^/]+}", _ConversationService_GetMessage0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{parent:conversations/[^/]+}/messages", _ConversationService_ListMessages0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{parent:conversations/[^/]+}/messages:batchGet", _ConversationService_BatchGetMessages0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/{parent:conversations/[^/]+}/messages", _ConversationService_CreateMessage0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/{message.name:conversations/[^/]+/messages/[^/]+}", _ConversationService_UpdateMessage0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/{name:conversations/[^/]+/messages/[^/]+}", _ConversationService_DeleteMessage0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{name:conversations/[^/]+/users/[^/]+}", _ConversationService_GetConversationUser0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{parent:conversations/[^/]+}/users", _ConversationService_ListConversationUsers0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{parent:conversations/[^/]+}/users:batchGet", _ConversationService_BatchGetConversationUsers0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/{parent:conversations/[^/]+}/users", _ConversationService_CreateConversationUser0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/{conversation_user.name:conversations/[^/]+/users/[^/]+}", _ConversationService_UpdateConversationUser0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/{name:conversations/[^/]+/users/[^/]+}", _ConversationService_DeleteConversationUser0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/{name:conversations/[^/]+}:replaceAvatar", _ConversationService_ReplaceConversationAvatar0_HTTP_Handler(srv))
}

func _ConversationService_GetConversation0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConversationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceGetConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConversation(ctx, req.(*GetConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Conversation)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_ListConversations0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConversationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceListConversations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConversations(ctx, req.(*ListConversationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListConversationsResponse)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_CreateConversation0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConversationRequest
		if err := ctx.Bind(&in.Conversation); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceCreateConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConversation(ctx, req.(*CreateConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Conversation)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_UpdateConversation0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConversationRequest
		if err := ctx.Bind(&in.Conversation); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceUpdateConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConversation(ctx, req.(*UpdateConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Conversation)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_DeleteConversation0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteConversationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceDeleteConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteConversation(ctx, req.(*DeleteConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_GetMessage0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMessageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceGetMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMessage(ctx, req.(*GetMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Message)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_ListMessages0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_BatchGetMessages0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchGetMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceBatchGetMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchGetMessages(ctx, req.(*BatchGetMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchGetMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_CreateMessage0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMessageRequest
		if err := ctx.Bind(&in.Message); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceCreateMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMessage(ctx, req.(*CreateMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Message)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_UpdateMessage0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMessageRequest
		if err := ctx.Bind(&in.Message); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceUpdateMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMessage(ctx, req.(*UpdateMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Message)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_DeleteMessage0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMessageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceDeleteMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMessage(ctx, req.(*DeleteMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_GetConversationUser0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConversationUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceGetConversationUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConversationUser(ctx, req.(*GetConversationUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationUser)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_ListConversationUsers0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConversationUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceListConversationUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConversationUsers(ctx, req.(*ListConversationUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListConversationUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_BatchGetConversationUsers0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchGetConversationUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceBatchGetConversationUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchGetConversationUsers(ctx, req.(*BatchGetConversationUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchGetConversationUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_CreateConversationUser0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConversationUserRequest
		if err := ctx.Bind(&in.ConversationUser); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceCreateConversationUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConversationUser(ctx, req.(*CreateConversationUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationUser)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_UpdateConversationUser0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConversationUserRequest
		if err := ctx.Bind(&in.ConversationUser); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceUpdateConversationUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConversationUser(ctx, req.(*UpdateConversationUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationUser)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_DeleteConversationUser0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteConversationUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceDeleteConversationUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteConversationUser(ctx, req.(*DeleteConversationUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_ReplaceConversationAvatar0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReplaceConversationAvatarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceReplaceConversationAvatar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReplaceConversationAvatar(ctx, req.(*ReplaceConversationAvatarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Conversation)
		return ctx.Result(200, reply)
	}
}

type ConversationServiceHTTPClient interface {
	// BatchGetConversationUsers Retrieves multiple conversation users.
	BatchGetConversationUsers(ctx context.Context, req *BatchGetConversationUsersRequest, opts ...http.CallOption) (rsp *BatchGetConversationUsersResponse, err error)
	// BatchGetMessages Retrieves multiple messages.
	BatchGetMessages(ctx context.Context, req *BatchGetMessagesRequest, opts ...http.CallOption) (rsp *BatchGetMessagesResponse, err error)
	// CreateConversation Creates a conversation.
	CreateConversation(ctx context.Context, req *CreateConversationRequest, opts ...http.CallOption) (rsp *Conversation, err error)
	// CreateConversationUser Creates a conversation user.
	CreateConversationUser(ctx context.Context, req *CreateConversationUserRequest, opts ...http.CallOption) (rsp *ConversationUser, err error)
	// CreateMessage Creates a message.
	CreateMessage(ctx context.Context, req *CreateMessageRequest, opts ...http.CallOption) (rsp *Message, err error)
	// DeleteConversation Deletes a conversation.
	DeleteConversation(ctx context.Context, req *DeleteConversationRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteConversationUser Deletes a conversation user.
	DeleteConversationUser(ctx context.Context, req *DeleteConversationUserRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteMessage Deletes a message.
	DeleteMessage(ctx context.Context, req *DeleteMessageRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetConversation Retrieves a conversation.
	GetConversation(ctx context.Context, req *GetConversationRequest, opts ...http.CallOption) (rsp *Conversation, err error)
	// GetConversationUser Retrieves a conversation user.
	GetConversationUser(ctx context.Context, req *GetConversationUserRequest, opts ...http.CallOption) (rsp *ConversationUser, err error)
	// GetMessage Retrieves a message.
	GetMessage(ctx context.Context, req *GetMessageRequest, opts ...http.CallOption) (rsp *Message, err error)
	// ListConversationUsers Lists user memberships in a conversation.
	ListConversationUsers(ctx context.Context, req *ListConversationUsersRequest, opts ...http.CallOption) (rsp *ListConversationUsersResponse, err error)
	// ListConversations Lists conversations.
	ListConversations(ctx context.Context, req *ListConversationsRequest, opts ...http.CallOption) (rsp *ListConversationsResponse, err error)
	// ListMessages Lists messages in a conversation.
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesResponse, err error)
	// ReplaceConversationAvatar Replaces the avatar of a conversation.
	ReplaceConversationAvatar(ctx context.Context, req *ReplaceConversationAvatarRequest, opts ...http.CallOption) (rsp *Conversation, err error)
	// UpdateConversation Updates a conversation.
	UpdateConversation(ctx context.Context, req *UpdateConversationRequest, opts ...http.CallOption) (rsp *Conversation, err error)
	// UpdateConversationUser Updates a conversation user.
	UpdateConversationUser(ctx context.Context, req *UpdateConversationUserRequest, opts ...http.CallOption) (rsp *ConversationUser, err error)
	// UpdateMessage Updates a message.
	UpdateMessage(ctx context.Context, req *UpdateMessageRequest, opts ...http.CallOption) (rsp *Message, err error)
}

type ConversationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewConversationServiceHTTPClient(client *http.Client) ConversationServiceHTTPClient {
	return &ConversationServiceHTTPClientImpl{client}
}

// BatchGetConversationUsers Retrieves multiple conversation users.
func (c *ConversationServiceHTTPClientImpl) BatchGetConversationUsers(ctx context.Context, in *BatchGetConversationUsersRequest, opts ...http.CallOption) (*BatchGetConversationUsersResponse, error) {
	var out BatchGetConversationUsersResponse
	pattern := "/v1/{parent=conversations/*}/users:batchGet"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceBatchGetConversationUsers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BatchGetMessages Retrieves multiple messages.
func (c *ConversationServiceHTTPClientImpl) BatchGetMessages(ctx context.Context, in *BatchGetMessagesRequest, opts ...http.CallOption) (*BatchGetMessagesResponse, error) {
	var out BatchGetMessagesResponse
	pattern := "/v1/{parent=conversations/*}/messages:batchGet"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceBatchGetMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateConversation Creates a conversation.
func (c *ConversationServiceHTTPClientImpl) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...http.CallOption) (*Conversation, error) {
	var out Conversation
	pattern := "/v1/conversations"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("conversation"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceCreateConversation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Conversation, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateConversationUser Creates a conversation user.
func (c *ConversationServiceHTTPClientImpl) CreateConversationUser(ctx context.Context, in *CreateConversationUserRequest, opts ...http.CallOption) (*ConversationUser, error) {
	var out ConversationUser
	pattern := "/v1/{parent=conversations/*}/users"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("conversationUser"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceCreateConversationUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.ConversationUser, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateMessage Creates a message.
func (c *ConversationServiceHTTPClientImpl) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...http.CallOption) (*Message, error) {
	var out Message
	pattern := "/v1/{parent=conversations/*}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("message"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceCreateMessage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Message, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteConversation Deletes a conversation.
func (c *ConversationServiceHTTPClientImpl) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/{name=conversations/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceDeleteConversation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteConversationUser Deletes a conversation user.
func (c *ConversationServiceHTTPClientImpl) DeleteConversationUser(ctx context.Context, in *DeleteConversationUserRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/{name=conversations/*/users/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceDeleteConversationUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteMessage Deletes a message.
func (c *ConversationServiceHTTPClientImpl) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/{name=conversations/*/messages/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceDeleteMessage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetConversation Retrieves a conversation.
func (c *ConversationServiceHTTPClientImpl) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...http.CallOption) (*Conversation, error) {
	var out Conversation
	pattern := "/v1/{name=conversations/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceGetConversation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetConversationUser Retrieves a conversation user.
func (c *ConversationServiceHTTPClientImpl) GetConversationUser(ctx context.Context, in *GetConversationUserRequest, opts ...http.CallOption) (*ConversationUser, error) {
	var out ConversationUser
	pattern := "/v1/{name=conversations/*/users/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceGetConversationUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMessage Retrieves a message.
func (c *ConversationServiceHTTPClientImpl) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...http.CallOption) (*Message, error) {
	var out Message
	pattern := "/v1/{name=conversations/*/messages/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceGetMessage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListConversationUsers Lists user memberships in a conversation.
func (c *ConversationServiceHTTPClientImpl) ListConversationUsers(ctx context.Context, in *ListConversationUsersRequest, opts ...http.CallOption) (*ListConversationUsersResponse, error) {
	var out ListConversationUsersResponse
	pattern := "/v1/{parent=conversations/*}/users"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceListConversationUsers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListConversations Lists conversations.
func (c *ConversationServiceHTTPClientImpl) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...http.CallOption) (*ListConversationsResponse, error) {
	var out ListConversationsResponse
	pattern := "/v1/conversations"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceListConversations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessages Lists messages in a conversation.
func (c *ConversationServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesResponse, error) {
	var out ListMessagesResponse
	pattern := "/v1/{parent=conversations/*}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationConversationServiceListMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReplaceConversationAvatar Replaces the avatar of a conversation.
func (c *ConversationServiceHTTPClientImpl) ReplaceConversationAvatar(ctx context.Context, in *ReplaceConversationAvatarRequest, opts ...http.CallOption) (*Conversation, error) {
	var out Conversation
	pattern := "/v1/{name=conversations/*}:replaceAvatar"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceReplaceConversationAvatar),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateConversation Updates a conversation.
func (c *ConversationServiceHTTPClientImpl) UpdateConversation(ctx context.Context, in *UpdateConversationRequest, opts ...http.CallOption) (*Conversation, error) {
	var out Conversation
	pattern := "/v1/{conversation.name=conversations/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("conversation"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceUpdateConversation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in.Conversation, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateConversationUser Updates a conversation user.
func (c *ConversationServiceHTTPClientImpl) UpdateConversationUser(ctx context.Context, in *UpdateConversationUserRequest, opts ...http.CallOption) (*ConversationUser, error) {
	var out ConversationUser
	pattern := "/v1/{conversation_user.name=conversations/*/users/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("conversationUser"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceUpdateConversationUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in.ConversationUser, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateMessage Updates a message.
func (c *ConversationServiceHTTPClientImpl) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...http.CallOption) (*Message, error) {
	var out Message
	pattern := "/v1/{message.name=conversations/*/messages/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("message"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationConversationServiceUpdateMessage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in.Message, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
