// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/velony-app/conversation/internal/application/usecase"
	"github.com/velony-app/conversation/internal/conf"
	"github.com/velony-app/conversation/internal/infrastructure/db/mysql"
	"github.com/velony-app/conversation/internal/infrastructure/server"
	"github.com/velony-app/conversation/internal/presentation/api"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, infrasturcture *conf.Infrasturcture, logger *slog.Logger) (*kratos.App, func(), error) {
	db, err := mysql.NewConnection(infrasturcture)
	if err != nil {
		return nil, nil, err
	}
	conversationRepository := mysql.NewConversationRepository(db)
	userRepository := mysql.NewUserRepository(db)
	conversationUserRepository := mysql.NewConversationUserRepository(db)
	unitOfWork := mysql.NewUnitOfWork(db)
	conversationUsecase := usecase.NewConversationUsecase(conversationRepository, userRepository, conversationUserRepository, unitOfWork)
	conversationUserUsecase := usecase.NewConversationUserUsecase(conversationRepository, userRepository, conversationUserRepository, unitOfWork)
	messageRepository := mysql.NewMessageRepository(db)
	messageUsecase := usecase.NewMessageUsecase(conversationUserRepository, messageRepository, unitOfWork)
	service := api.NewService(conversationUsecase, conversationUserUsecase, messageUsecase)
	serverMetrics, err := server.NewServerMetrics()
	if err != nil {
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, service, serverMetrics)
	httpServer := server.NewHTTPServer(confServer, service, serverMetrics)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
